name: info_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: ^0.16.1
  shared_preferences: ^0.5.7+2
  flutter_mobx: ^1.1.0
  dio: ^3.0.9
  mobx: ^1.2.0
  flutter_modular: ^1.2.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher_info_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_launcher_info_app.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/C-99.jpg
    - assets/images/C-97.jpg
    - assets/images/Both.jpg
    - assets/images/man-pilot-w.png
    - assets/images/man-pilot-m.png
    - assets/images/man-pilot-mm.png
    - assets/images/man-pilot-mmm.png
    - assets/images/woman-pilot-w.png
    - assets/images/man-attendant-w.png
    - assets/images/man-attendant-m.png
    - assets/images/man-attendant-mm.png
    - assets/images/man-attendant-mmm.png
    - assets/images/woman-attendant-w.png
    - assets/images/man-mechanic-w.png
    - assets/images/man-mechanic-m.png
    - assets/images/man-mechanic-mm.png
    - assets/images/man-mechanic-mmm.png
    - assets/images/woman-mechanic-w.png
    - assets/images/man-doctor-w.png
    - assets/images/woman-doctor-w.png
    - assets/images/condor.png
    - assets/images/icon_launcher_info_app.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
         
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  dev: flutter pub run build_runner build --delete-conflicting-outputs
  clr: flutter pub run build_runner clean
